#!/usr/bin/env node
/**
 * Derives a real <lastmod> for every sitemap partition from git.
 *
 * The audit found none at all: not on the twenty-odd children the index names,
 * and not on a single <url> in any of them. lastmod is a crawl-scheduling hint,
 * and with none of it Google has nothing to distinguish a page edited this
 * morning from one untouched for a year - on a site of this size that is the
 * difference between recrawling what changed and recrawling at random.
 *
 * The date has to be true or it is worse than absent. A build timestamp would
 * mark all 152 routes as modified on every deploy, which is the fabricated
 * freshness crawlers learn to discount. Git already records when each
 * partition's data and route files actually changed, so that is the source.
 *
 * It refuses to guess. On a shallow clone every file present at the graft
 * commit reports that commit's date, overstating freshness for anything older,
 * so a shallow repo (or no git) keeps the committed map rather than
 * overwriting it with worse data.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(root, "src/generated/lastmod.ts");
const CHECK = process.argv.includes("--check");

/**
 * Each key is a sitemap partition; the values are the files whose content
 * decides what those URLs say. Route components count: a change to
 * anime.$slug.tsx changes every anime page it renders.
 */
const GROUPS = {
  pages: ["src/data/explore-pages.ts", "src/lib/sitemap.ts", "src/routes/index.tsx"],
  products: [
    "src/data/store-products.ts",
    "src/data/store-pricing.ts",
    "src/routes/store_.$slug.tsx",
    "src/routes/store.tsx",
  ],
  anime: [
    "src/data/animes.ts",
    "src/data/arcs.ts",
    "src/lib/anime-sections.ts",
    "src/routes/anime.$slug.tsx",
    "src/routes/anime.$slug_.$section.tsx",
  ],
  episodes: ["src/data/episodes.ts", "src/routes/anime_.$slug.episode.$num.tsx"],
  articles: [
    "src/data/articles.ts",
    "src/data/articles-extra.ts",
    "src/data/articles-longform.ts",
    "src/routes/article.$slug.tsx",
  ],
  characters: ["src/data/characters.ts", "src/routes/character.$slug.tsx"],
  taxonomy: [
    "src/data/categories.ts",
    "src/routes/category.$slug.tsx",
    "src/routes/genre.$slug.tsx",
    "src/routes/studio.$slug.tsx",
  ],
  ar: ["src/data/ar-guides.ts"],
  codes: ["src/routes/$locale.codes.$slug.tsx", "src/routes/codes.$slug.tsx"],
  catalog: [
    "scripts/ingest-anilist.mjs",
    "scripts/ingest-steam.mjs",
    "scripts/ingest-manga.mjs",
    "scripts/derive-facts.mjs",
  ],
  matrix: ["src/lib/catalog/matrix.ts", "scripts/write-matrix-index.mjs"],
  manga: ["scripts/ingest-manga.mjs"],
};

const git = (args) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim();

function render(dates, commit) {
  const values = Object.values(dates).sort();
  const rows = Object.keys(dates)
    .sort()
    .map((key) => {
      const name = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
      return `  ${name}: ${JSON.stringify(dates[key])},`;
    })
    .join("\n");
  return `// GENERATED by scripts/build-lastmod.mjs - do not edit by hand.
// The date of the last commit touching the files that generate each sitemap
// partition. Regenerate with: npm run build:lastmod
// Source commit: ${commit}

export const PARTITION_LASTMOD: Record<string, string> = {
${rows}
};

/** Newest date in the map; used for index children with no partition of their own. */
export const NEWEST_LASTMOD: string | undefined = ${values.length ? JSON.stringify(values.at(-1)) : "undefined"};
`;
}

function bail(why) {
  const kept = existsSync(OUT);
  console.log(`[lastmod] ${why}`);
  console.log(
    kept
      ? "[lastmod] keeping the committed src/generated/lastmod.ts rather than writing worse dates."
      : "[lastmod] no committed map to fall back on; sitemap entries will omit lastmod.",
  );
  if (CHECK) process.exit(kept ? 0 : 1);
  if (!kept) writeFileSync(OUT, render({}, "unknown"));
  process.exit(0);
}

try {
  git(["rev-parse", "--git-dir"]);
} catch {
  bail("not a git checkout.");
}
if (git(["rev-parse", "--is-shallow-repository"]) === "true") {
  bail("shallow clone - per-file dates would be floored at the graft commit.");
}

const dates = {};
let missing = 0;
for (const [group, files] of Object.entries(GROUPS)) {
  const found = files.filter((file) => existsSync(resolve(root, file)));
  for (const file of files) {
    if (!found.includes(file)) {
      console.warn(`[lastmod] ${group}: ${file} does not exist — the GROUPS list is stale.`);
      missing += 1;
    }
  }
  if (!found.length) continue;
  const seen = found
    .map((file) => git(["log", "-1", "--format=%cs", "--", file]))
    .filter(Boolean)
    .sort();
  if (seen.length) dates[group] = seen.at(-1);
}

const commit = git(["rev-parse", "--short", "HEAD"]);
const next = render(dates, commit);
const prev = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
if (prev !== next) {
  if (CHECK) {
    console.error("[lastmod] src/generated/lastmod.ts is stale. Run: npm run build:lastmod");
    process.exit(1);
  }
  writeFileSync(OUT, next);
}
console.log(`[lastmod] ${Object.keys(dates).length} partition(s) dated from git at ${commit}.`);
for (const [group, date] of Object.entries(dates).sort()) console.log(`  ${group}: ${date}`);
if (missing) console.log(`[lastmod] ${missing} listed file(s) missing — fix GROUPS.`);
