import assert from 'node:assert/strict';
import {fresh,restore,beginUpgrade,finishUpgrade,victory,daily,challengeFrom,seedRandom} from '../public/harbor/rules.mjs';
const s=fresh('ليث','جزيرة الفجر');
assert.equal(restore('{bad'),null);
assert.equal(restore(JSON.stringify({...s,gold:-999,cannon:999})).gold,0);
assert.equal(restore(JSON.stringify({...s,cannon:999})).cannon,20);
const building=beginUpgrade(s,'cannon',1000);
assert.equal(building.gold,70);
assert.equal(beginUpgrade(building,'harbor',1000),null);
assert.equal(beginUpgrade(s,'__proto__'),null);
assert.equal(finishUpgrade(building,1500),null);
assert.equal(finishUpgrade(building,1500,true),null);
assert.equal(finishUpgrade({...building,gems:5},1500,true).gems,0);
const finished=finishUpgrade(building,21000);
assert.equal(finished.cannon,2);
assert.equal(finishUpgrade(finished,22000),null);
assert.equal(victory(s,100).gems,3);
assert.equal(victory(s,50).gems,1);
const next=daily({...s,lastDay:'2026-09-09'},new Date('2026-09-10T12:00:00Z'));
assert.equal(next.streak,2);
assert.deepEqual(daily(next,new Date('2026-09-10T13:00:00Z')),next);
assert.equal(challengeFrom('?challenge=<script>'),null);
assert.equal(challengeFrom('?challenge=123'),123);
const a=seedRandom(123),b=seedRandom(123);
assert.deepEqual(Array.from({length:20},a),Array.from({length:20},b));
console.log('Harbor: save validation, upgrade payments, timer completion, rewards and challenge seeds passed.');
